# Generated by Django 4.1.4 on 2022-12-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_pull_delete_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='Option')),
                ('pull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull', to='webapp.pull', verbose_name='Pull')),
            ],
        ),
    ]
