# Generated by Django 4.1.4 on 2022-12-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Answered')),
                ('option_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_fk', to='webapp.choice', verbose_name='Option')),
                ('pull_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_fk', to='webapp.pull', verbose_name='Pull')),
            ],
        ),
    ]
